-- ============================================================================
-- Vista: TicketsPackage
-- Dataset: firestore_export
-- Proyecto: casla-fanhub-admin-prod
-- Descripción: Extrae y transforma datos de paquetes de tickets desde Firestore
-- ============================================================================

SELECT                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    document_id,                                                                                                                                                                                                                                                                                                                                                                                                                                          
    CAST(JSON_EXTRACT_SCALAR(data, '$.activityId') AS STRING) AS activity_id,                                                                                                                                                                                                                                                                                                                                                                             
    CAST(JSON_EXTRACT_SCALAR(data, '$.adminUserId') AS STRING) AS admin_user_id,                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    -- created_at_timestamp (TIMESTAMP, útil para hora)                                                                                                                                                                                                                                                                                                                                                                                                   
    IFNULL(                                                                                                                                                                                                                                                                                                                                                                                                                                               
      COALESCE(                                                                                                                                                                                                                                                                                                                                                                                                                                           
        TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.createdAt._seconds') AS INT64)),                                                                                                                                                                                                                                                                                                                                                         
        SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%S%Ez', JSON_EXTRACT_SCALAR(data, '$.createdAt')),                                                                                                                                                                                                                                                                                                                                                           
        SAFE.PARSE_TIMESTAMP('%d de %B de %Y, %I:%M:%S %p',                                                                                                                                                                                                                                                                                                                                                                                               
          REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT_SCALAR(data, '$.createdAt'),' UTC-3', ''),'p.m.', 'PM'),'Enero', 'January'),'Febrero', 'February'),'Marzo', 'March'),'Abril', 'April'),'Mayo', 'May'),'Junio', 'June'),'Julio', 'July'),'Agosto', 'August'),'Septiembre', 'September'),'Octubre', 'October'),'Noviembre', 'November'),'Diciembre', 'December'),    
        'America/Argentina/Buenos_Aires')                                                                                                                                                                                                                                                                                                                                                                                                                 
      ),                                                                                                                                                                                                                                                                                                                                                                                                                                                  
      TIMESTAMP('1970-01-01 00:00:00 UTC')                                                                                                                                                                                                                                                                                                                                                                                                                
    ) AS created_at_timestamp,                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    -- **** CAMBIO: created_date ahora es de tipo DATE (no STRING formateado) ****                                                                                                                                                                                                                                                                                                                                                                        
    DATE(IFNULL( -- Usamos DATE() para convertir TIMESTAMP a DATE                                                                                                                                                                                                                                                                                                                                                                                         
      COALESCE(                                                                                                                                                                                                                                                                                                                                                                                                                                           
        TIMESTAMP_SECONDS(SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.createdAt._seconds') AS INT64)),                                                                                                                                                                                                                                                                                                                                                         
        SAFE.PARSE_TIMESTAMP('%Y-%m-%dT%H:%M:%S%Ez', JSON_EXTRACT_SCALAR(data, '$.createdAt')),                                                                                                                                                                                                                                                                                                                                                           
        SAFE.PARSE_TIMESTAMP('%d de %B de %Y, %I:%M:%S %p',                                                                                                                                                                                                                                                                                                                                                                                               
            REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(JSON_EXTRACT_SCALAR(data, '$.createdAt'),' UTC-3', ''),'p.m.', 'PM'),'Enero', 'January'),'Febrero', 'February'),'Marzo', 'March'),'Abril', 'April'),'Mayo', 'May'),'Junio', 'June'),'Julio', 'July'),'Agosto', 'August'),'Septiembre', 'September'),'Octubre', 'October'),'Noviembre', 'November'),'Diciembre', 'December'),  
        'America/Argentina/Buenos_Aires')                                                                                                                                                                                                                                                                                                                                                                                                                 
      ),                                                                                                                                                                                                                                                                                                                                                                                                                                                  
      TIMESTAMP('1970-01-01 00:00:00 UTC')                                                                                                                                                                                                                                                                                                                                                                                                                
    )) AS created_date, -- Renombrado a 'created_date'                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    CAST(JSON_EXTRACT_SCALAR(data, '$.eventId') AS STRING) AS event_id,                                                                                                                                                                                                                                                                                                                                                                                   
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.finalTotal') AS NUMERIC) AS final_total,                                                                                                                                                                                                                                                                                                                                                                       
    CAST(JSON_EXTRACT_SCALAR(data, '$.id') AS STRING) AS ticket_package_id,                                                                                                                                                                                                                                                                                                                                                                               
    CAST(JSON_EXTRACT_SCALAR(data, '$.isDeleted') AS BOOL) AS is_deleted,                                                                                                                                                                                                                                                                                                                                                                                 
    CAST(JSON_EXTRACT_SCALAR(data, '$.isRenewal') AS BOOL) AS isRenewal,                                                                                                                                                                                                                                                                                                                                                            
    CAST(JSON_EXTRACT_SCALAR(data, '$.memberId') AS STRING) AS memberId,                                                                                                                                                                                                                                                                                                                                                                                  
    CAST(JSON_EXTRACT_SCALAR(data, '$.paymentMethod') AS STRING) AS payment_method,                                                                                                                                                                                                                                                                                                                                                                       
    JSON_EXTRACT(data, '$.partialPaymentDetails') AS partialPaymentDetails,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    CAST(JSON_EXTRACT_SCALAR(data, '$.paymentId') AS STRING) AS payment_id,                                                                                                                                                                                                                                                                                                                                                                               
    CAST(JSON_EXTRACT_SCALAR(data, '$.paymentPlanId') AS STRING) AS paymentPlanId,                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    CAST(JSON_EXTRACT_SCALAR(data, '$.placeId') AS STRING) AS place_id,                                                                                                                                                                                                                                                                                                                                                                                   
    CAST(JSON_EXTRACT_SCALAR(data, '$.sectorId') AS STRING) AS sector_id,                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    TRIM(REPLACE(REPLACE(REPLACE(JSON_EXTRACT(data, '$.promotions[0]'), '{', ''), '}', ''), '"', '')) AS promo_discount_by_payment_method,                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    package_ticket_item_id_val AS package_ticket_item_id,                                                                                                                                                                                                                                                                                                                                                                                                 
    SAFE_CAST(JSON_EXTRACT_SCALAR(data, '$.ticketsCount') AS NUMERIC) AS total_tickets_in_package,                                                                                                                                                                                                                                                                                                                                                        
    CAST(JSON_EXTRACT_SCALAR(data, '$.status') AS STRING) AS status                                                                                                                                                                                                                                                                                                                                                                                       
  FROM                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    `casla-fanhub-admin-prod.firestore_export.stream_raw_latest`                                                                                                                                                                                                                                                                                                                                                                                          
  LEFT JOIN                                                                                                                                                                                                                                                                                                                                                                                                                                               
    UNNEST(`casla-fanhub-admin-prod`.firestore_export.ExtractTicketIds(data)) AS package_ticket_item_id_val                                                                                                                                                                                                                                                                                                                                               
  ON                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    TRUE                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  WHERE                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    document_name LIKE 'projects/casla-fanhub-admin-prod/databases/(default)/documents/TicketsPackage/%'
